### PR TITLE
OCaml language support

### PR DESCRIPTION
**Pull request by Freyr666**
New language

### CODE REVIEW

**Comment by partouf** [comment]
hi, thanks for doing this! But there's a couple of problems with the way you're going about this.
Firstly, small detail, tar -Jxf is for .bz2 files, tar -zxf for .gz files.
But the main issue is that this code would build the compiler on the node that isn't really meant for long build processes (and it definitely is lengthy).
If there are official prebuilt binaries, then those are prefered, but if not, a specific Dockerfile for builds is required to setup the environment properly. (when I tried to build it on my regular vm for CE, I got a strange error)
Example can be found in https://github.com/mattgodbolt/compiler-explorer-image/tree/master/clang
@mattgodbolt can help if needed

**Comment by Freyr666** [comment]
@partouf ups, sorry for tar opts. There are no prebuilt binaries, unfortunately. Honestly, I've just copied a Haskell example, is there a corresponding dockerfile for haskell (or is some common dockerfile reused)?

**Comment by mattgodbolt** [comment]
Hi @Freyr666 -- let me know if I can assist here, or take this on. I think your example shows enough of how to do it that if you're not familiar with Docker I can just take this one. Let me know :)

**Comment by Freyr666** [comment]
@mattgodbolt Oh, this would be very kind of you. The delay was due to I had no time to dive into the Docker.

**Comment by mattgodbolt** [comment]
Have built a docker image and built and installed the apps:

```
ubuntu@admin-node ~/compiler-explorer-image> ls -ld /opt/compiler-explorer/ocam*
drwxr-xr-x 5 root root 6144 Jan 23 14:21 /opt/compiler-explorer/ocaml-4.04.2/
drwxr-xr-x 5 root root 6144 Jan 23 15:08 /opt/compiler-explorer/ocaml-4.06.1/
drwxr-xr-x 5 root root 6144 Jan 23 16:31 /opt/compiler-explorer/ocaml-4.07.1/
drwxr-xr-x 5 root root 6144 Jan 23 15:10 /opt/compiler-explorer/ocaml-4.07.1-flambda/
```

Will take a look at https://github.com/mattgodbolt/compiler-explorer/pull/1225 when I get a mo :)

**Comment by Freyr666** [comment]
Awesome, thanks for help.

**Comment by mattgodbolt** [comment]
@Freyr666 If I didn't "configure" them ahead of time to be the installation directory then things like `ocaml` didn't run (as their shebangs were all `/root/staging/bin/ocamlrun` which is not where they're ultimately installed.

Any thoughts? Perhaps we don't need to run `ocaml` ? I'll be honest I didn't check much other than "did `ocaml --version` work :)"

**Comment by Freyr666** [comment]
@mattgodbolt

Well, we don't need bytecode executables anyway, but that is rather strange strange. For example here I have an ocaml directory in my home directory, if I do 
  
    cd ~/contrib/ocaml
    ./configure -prefix /opt
    make world.opt
    
then 'head -c 20 ~/contrib/ocaml/ocaml' gives me '/opt/bin/ocaml'

>If I didn't "configure" them ahead of time to be the installation directory

You mean you configure --prefix as install dir? You definitely don't need that, you don't need to run 'ocaml' or anything else before 'make install' would install them to their final destination.

**Comment by mattgodbolt** [comment]
I think we're agreeing here: your example shows that the conifguring makes the shebang point at the `-prefix`.

YeS: I do need to manually reallocate: I build the image (the tarball) from a throwaway virtual docker machine. I then untar it where it needs to live on the installed machine (which in general, and for all other compilers I build, is _not_ where it was built). Most compilers I "install" to `/root/staging`, then I `tar` that, then `untar` it as `/opt/compiler-explorer/where/I/need/that/compiler/to/go`. That way the build process doesn't need to care about where the install process wants to put it.

It's not a problem here: it was easy to make the staging directory the same as the installation directory for `ocaml`. I'll take a look at merging the sister repo changes soon :)

**Pull request closed without merging**
