### PR TITLE
New gcc-cross w/ GCC for ARM

### PR DESCRIPTION
**Pull request by dbroemmel**
Dockerfile is extended to use a git version of crosstool-ng in order to build a more recent set of compilers. The compiler `*.config`s have been adapted w/ a `ct-ng oldconfig` and moved to `build/new`. Files for ct-ng-1.23 are moved to `build/old`, the ones prior to that to `build/even-older` (which can probably be deleted as it doesn't run on Ubuntu 18.04.

The config files within `build/new` have been tested, seem to work, and now contain gfortran. After changing kernel version and disabling Ada, Objective C/C++, and Go, the new PPC config from #127 also seems to work.

Uploading to s3 storage and the installation procedure is not tested. There is also a clone of `admin-daily-builds.sh` that should build all cross-compilers (also not tested).

With the ct-ng oldconfig, I was prompted for a number of version choices for kernel, libc, and pre-requisite libraries for GCC. I tweaked this a little to successfully build the compilers, but largely have no idea what impact this might have. Especially the kernel version seems arbitrary.

### CODE REVIEW

**Comment by grooverdan** [comment]
Ha, was thinking the same thing https://github.com/grooverdan/compiler-explorer-image/commit/6b37b8f7efdfba8e17e2f887e1c66fe3cab23c6e.

Totally agree with old/even-older/1.22.0, even with the patch I added in the commit, the arm/avr compilers generate a SIGFPE during the compilation of ppl-0.11.2. Even powerpc-4.8.5 fails in gcc-final with `cfns.gperf:101:1: error: 'const char* libc_name_p(const char*, unsigned int)' redeclared inline with 'gnu_inline' attribute`.

All except the arm64 ones (failed in binutils/zlib/configure script being truncated - just odd) of new/1.23.0 managed to compile on ct-ng-git/latest.

Only needed to remove ADA from the PPC64 builds in #127 like https://github.com/grooverdan/compiler-explorer-image/commit/fafcbfaca1c8dc75e44c94813cf6940321992c57, and thanks for testing.

Been testing with:
<pre>
 for a in *.config; do b=${a%.config}; docker rm $b;   docker run --name $b -v gcc-cross-opt:/opt/.build mattgodbolt/gcc-cross:latest ./build.sh ${b%%-*} ${b#*-}; done
</pre>
note: haring a volume of just /opt/.build/tarballs would of been much less prone to conflicts in tools and /opt/.build/$arch.

**Comment by dbroemmel** [comment]
@grooverdan I like the idea of naming the config directories after the ct-ng version, makes things a lot clearer. From a previous exchange with @mattgodbolt I seem to remember that the cross-compilers are not (re-)built automatically at fixed times. Instead the build is run once, the resulting compilers than used from that point on. So I wasn't too worried about rebuilding all the previous versions/architectures since they are there already.

I also didn't bother with patching anything or looking into errors during compilation. It either worked or it didn't. I stopped after tweaking the config files to ct-ng.

You say the arm64 compilers did not build for you? I'm pretty sure I tested them with the changes in my branch. Also, a colleague of mine has been asking about the latest compilers for Power, but I thought I don't touch those and rather leave that to you.

> note: haring a volume of just /opt/.build/tarballs would of been much less prone to conflicts in tools and /opt/.build/$arch.

I'm afraid I don't understand this comment here.

**Comment by grooverdan** [comment]
Ok. I'll put my commit as a separate PR. Questions about what you have here that I'll incorporate:
* `set -exuo pipefail` will probably include that in build.sh
* admin-cross-builds.sh - was this from @mattgodbolt ? I missed the bit that triggers all the builds so I guess this is it. Probably could generate the compiler list from the (functional?) config files.
* like the apt-get clean/check
* what does installing python-dev achieve?

Arm64 failures might of been as a result of me sharing the /opt/.build as a volume between concurrently running docker images. Testing it again now.

If your colleague wants anything in particular in the latest Power compilers please leave a note on #127 or email me.

**Comment by dbroemmel** [comment]
>     * `set -exuo pipefail` will probably include that in build.sh
>     * admin-cross-builds.sh - was this from @mattgodbolt ? I missed the bit that triggers all the builds so I guess this is it. Probably could generate the compiler list from the (functional?) config files.
I added `admin-cross-builds.sh` in the hope it would make building the cross-compilers a little simpler. It's adopted from `admin-daily-builds.sh` that is in repository. Generating a list from the config files might be a nice idea. I guess that really depends on how often/when the cross-compilers will in the end be built. That's not my call.

>     * like the apt-get clean/check
I had to add this because I had failing apt-get's without that. Possibly because some bits of the Dockerfile had been cached and it was using outdated package lists. I'm guessing here since I don't know how docker works in detail. So it may not be necessary.

>     * what does installing python-dev achieve?
Don't know? I copied whatever [ct-ng](https://crosstool-ng.github.io/docs/os-setup/) suggested as necessary packages to build it on Ubuntu.

**Comment by dbroemmel** [comment]
> If your colleague wants anything in particular in the latest Power compilers please leave a note on #127 or email me.

Nothing in particular, just updated plain compilers.

**Comment by mattgodbolt** [comment]
Hi @dbroemmel - thanks for this! Sorry I haven't looked at this earlier. Will try to get to it tonight and then see how the builds pan out!

**Comment by mattgodbolt** [comment]
Yes, definitely having a list of the "expected" builds this should support is handy... the `admin-cross-builds.sh` is the thing I probably need the most. Though its name is misleading I think (I wouldn't run it on the admin node), but that's far from the point :) Thanks for the reply. If @dbroemmel doesn't have anything to add I'll steal the configurations from admin-cross-builds and run them

**Comment by grooverdan** [comment]
From the `gcc-cross/build/{1.22.0,1.23.0,latest}` directories I was crudely running:

<pre>for a in *config; do
   b=${a%.config}
  docker rm $b
  docker run --name $b -v gcc-cross-opt:/opt/.build/tarballs mattgodbolt/gcc-cross:latest ./build.sh ${b%%-*} ${b#*-}
done
</pre>

`gcc-cross-opt` was a created (`docker volume create gcc-cross-opt`) to avoid duplicate downloads. Never got to making a nicer script like above.

Hack and use as you see fit.

**Comment by mattgodbolt** [comment]
Fabulous! Thanks @grooverdan!

**Comment by mattgodbolt** [comment]
I have to pack up for the night, but tried something similar, and:

```
++ basename gcc-cross/build/1.22.0/avr-4.6.4.config
+ a=avr-4.6.4.config                                                                                                                        
+ b=avr-4.6.4
+ docker run --rm -v gcc-cross-opt:/opt/.build/tarballs mattgodbolt/gcc-cross:latest ./build.sh avr 4.6.4 s3://compiler-explorer/opt/   
++ pwd                                            
+ ROOT=/opt                                          
....
[INFO ]  Installing MPFR for host: done in 23.53s (at 03:47)
[INFO ]  =================================================================
[INFO ]  Installing PPL for host
[EXTRA]    Configuring PPL
[EXTRA]    Building PPL
[ERROR]    /opt/.build/src/ppl-0.11.2/src/Row.inlines.hh:118:23: error: unknown array size in delete
...
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'crosstool-ng-1.22.0/docs/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 5:14.49)
[05:15] / make[1]: *** [build] Error 2
/opt/crosstool-ng-1.22.0/ct-ng:152: recipe for target 'build' failed
/opt/crosstool-ng-1.22.0/ct-ng:155: recipe for target 'build.4' failed
make: *** [build.4] Error 2
```

so, sadly doesn't look like it's working (unless I'm running a bad build here?) Any thoughts?

**Comment by grooverdan** [comment]
Its not you, I get the same fault. Seems to have been a consequence of moving to bionic. I did change the `FROM` to 16.04, took out my 1.22.0 patch, and gcc-cross/build/1.22.0/avr-4.6.4.config will build. I'm assuming the rest will follow suit.

Other fails are: https://github.com/mattgodbolt/compiler-explorer-image/pull/129#issuecomment-435324350. While it would be nice to make these old compilers I suspect the bionic gcc has just been updated too much to cope with some older source trees. Even the `1.23.0/*{6.3.0|7.1.0}*` trigger a compile failure that was found the ct-ng issue tracker (that's fixed in `latest/*{6.4.0|7.3.0}`). Might need to maintain `mattgodbolt/gcc-cross:16.04` for reproducing older compilers.

The only new configurations builds are the ones in `gcc-cross/build/latest`, and those definitely build.

**Comment by dbroemmel** [comment]
@mattgodbolt I had a quick look if there's anything in this PR not already included by #127, #130, or #131. As @grooverdan said it's only the 'convenience script'. I modeled the script after one of yours and found that easier to then control which versions to build. Since you are initiating those builds this is up to you how to do this (I remember when first looking at the collection of scripts I didn't find one building the cross-compilers, c.f. https://github.com/mattgodbolt/compiler-explorer/pull/948#discussion_r201007721, https://github.com/mattgodbolt/compiler-explorer/pull/948#discussion_r202525564).

So, no need to merge this one, I'll close it.

Thanks for the comments and merging the other PRs.

**Pull request closed without merging**
