### PR TITLE
Add advance-toolchain-10.0 to base image for ppc64 and ppc64le C++ and go compiler

### PR DESCRIPTION
**Pull request by grooverdan**
Added to base as this adds a c++ compiler as well as gccgo.

Provides AT compiler for mattgodbolt/compiler-explorer/issues/205 as suggested by @munroesj

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Hi!

Thanks so much for this PR and the others.  However, can I ask that this PR be changed. I'm trying to minimize the amount of stuff installed in Docker -- you'll note that no compilers are installed into the image any more. When you have >40Gb of compilers, building them into a docker image is very slow; generates giant images that are slow to boot from and distribute, and slows down the adding of new compilers (as the build time for the image grows each added compiler).

Instead, can you add to [the update_compiler](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_compilers.sh) script? This is used to populate an externally-mounted NFS drive /opt/compiler-explorer/*.  Some extra rationale on this is on my [blog](https://xania.org/201609/how-compiler-explorer-runs-on-amazon) but I appreciate there's absolutely no documentation on this...

Thanks so much: I hope this change can be made to work in `/opt/compiler-explorer` instead!

Thanks, Matt

**Comment by munroesj** [comment]
AT has public GCC branches for each release that we maintain. You should contact Raphael Moreira Zinsly (rzinsly@br.ibm.com) for the build scripts

**Comment by grooverdan** [comment]
OK. Will look next week. Thanks for clarifying /opt/compiler-explorer as the mount point. Using https://github.com/advancetoolchain/advance-toolchain and using DESTDIR seems easy enough. Thanks for the quick response.

**Comment by mattgodbolt** [comment]
Thanks so much for being understanding! It took a long time to slowly wean myself all the `apt-get` compilers in favour of this approach, and I'm sorry it's a pain!

**Comment by grooverdan** [comment]
#127

**Pull request closed without merging**
