### PR TITLE
Add ct-ng gcc-6.3.0 & gcc-7.1.0 for ARM & ARM64

### PR DESCRIPTION
**Pull request by lucvoo**
This add support for newer GCC version for ARM & ARM64.

The crosstool configs produce working compilers but as I don't understand well your environment I can't test them with the same setup.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks for this! I'm busy at the moment but will merge, build and test in the next day or two!

**Comment by lucvoo** [comment]
It's me that thank you for this wonderful tool!
There is no hurry.

**Comment by mattgodbolt** [comment]
Thanks for this: 6.3 is in and merged.

7.1 didn't work as the `docker` image here needs to be updated to pull down a trunk crosstool-ng: the 1.23 version doesn't support it (yet)!

**Comment by lucvoo** [comment]
Thanks!
Yes, I see now for 7.1 :(  gcc-cross/build/new is for ct-ng 1.23 which is from April and I used the head from June.
It seems that the ct-ng guys do a release like every 6 months or so but no snapshots to download.
Would you like a patch who will fetch the current head directly from github, maybe reserved it for configs in gcc-cross/build/cur or something like that?

**Comment by mattgodbolt** [comment]
Something like that would be cool: but I'd prefer it to check out a particular SHA sum (so the docker build is reproducible and doesn't change depending on when you run it).

**Pull request merged**
