### PR TITLE
Set compiler-explorer.com to https

### PR DESCRIPTION
**Pull request by partouf**
This is setup in the console manually and it seems to work

### CODE REVIEW

**Comment by apmorton** [comment]
add this to `alb.tf` to reflect the additional cert added to the listener

```
resource "aws_lb_listener_certificate" "compiler-explorer-alb-listen-https-ce-cert" {
  listener_arn    = "${aws_alb_listener.compiler-explorer-alb-listen-https.arn}"
  certificate_arn = "arn:aws:acm:us-east-1:052730242331:certificate/7abed4ab-ecfc-4020-8f73-f255fd82f079"
}
```

(I guessed on the certificate_arn based on cloudfront terraform)

**Comment by partouf** [comment]
I did add the compiler-explorer.com certificate to the load balancer beforehand, I think that needs to be setup in terraform as well somewhere around here -> https://github.com/mattgodbolt/compiler-explorer-image/blob/f01ab0670fc819af1ef2d4df4d832475aab75747/terraform/alb.tf#L74

**Comment by partouf** [comment]
> add this to `alb.tf` [here](https://github.com/mattgodbolt/compiler-explorer-image/blob/f01ab0670fc819af1ef2d4df4d832475aab75747/terraform/alb.tf#L76) to reflect the additional cert added to the listener
> 
> ```
> resource "aws_lb_listener_certificate" "compiler-explorer-alb-listen-https-ce-cert" {
>   listener_arn    = "${aws_alb_listener.compiler-explorer-alb-listen-https.arn}"
>   certificate_arn = "arn:aws:acm:us-east-1:052730242331:certificate/7abed4ab-ecfc-4020-8f73-f255fd82f079"
> }
> ```
> 
> (I guessed on the certificate_arn based on cloudfront terraform)

Done, thanks. Arn was correct

**Comment by mattgodbolt** [comment]
Merged: `terraform` thinks that not all changes have been applied:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_lb_listener_certificate.compiler-explorer-alb-listen-https-ce-cert
      id:              <computed>
      certificate_arn: "arn:aws:acm:us-east-1:052730242331:certificate/7abed4ab-ecfc-4020-8f73-f255fd82f079"
      listener_arn:    "arn:aws:elasticloadbalancing:us-east-1:052730242331:listener/app/GccExplorerApp/4a4513393260c7c5/1dc0ebb4dd9eeb53"


Plan: 1 to add, 0 to change, 0 to destroy.

```

**Comment by mattgodbolt** [comment]
This may be due to you having already added it: will adopt it (one thing not held in source control is the mapping between AWS resources and the names in terraform)

**Comment by mattgodbolt** [comment]
Yay! I see you added it...and you fixed the original issue which was the certificates! Hooray!

**Pull request merged**
