### PR TITLE
Add CUDA 10.0, 10.1, and 10.1 Update 1

### PR DESCRIPTION
**Pull request by benbarsdell**

### CODE REVIEW

**Comment by mattgodbolt** [comment]
The 10.1 update 1 gets a 404
 local URL=https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux

this is a 404 on NVidia's site.

**Comment by mattgodbolt** [comment]
full dump of the install:
```
+ rm -rf /tmp/cuda
+ popd
/opt/compiler-explorer
+ install_cuda https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux 10.1.105
+ local URL=https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux
+ mkdir -p cuda
+ pushd cuda
/opt/compiler-explorer/cuda /opt/compiler-explorer
++ pwd
+ local DIR=/opt/compiler-explorer/cuda/10.1.105
+ [[ ! -d /opt/compiler-explorer/cuda/10.1.105 ]]
+ rm -rf /tmp/cuda
+ mkdir /tmp/cuda
+ fetch https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux
++ mktemp
+ local temp=/tmp/tmp.auw97j2ZAQ
+ curl -s -L https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux -o /tmp/tmp.auw97j2ZAQ
+ cat /tmp/tmp.auw97j2ZAQ
+ rm /tmp/tmp.auw97j2ZAQ
+ sh /tmp/cuda/combined.sh --extract=/tmp/cuda
/tmp/cuda/combined.sh: 1: /tmp/cuda/combined.sh: cannot open !DOCTYPE: No such file
```

**Comment by mattgodbolt** [comment]
Oh! apologies, this is the 10.1 one., not 10.1u1

**Comment by apmorton** [comment]
```
install_cuda https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux.run 10.1.105
install_cuda https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.168_418.67_linux.run 10.1.168
```

**Comment by mattgodbolt** [comment]
missing the `.run`? I'll give it a go!

**Comment by mattgodbolt** [comment]
Worked a bit better, but still failed.

```
+ local temp=/tmp/tmp.zjJFZXEI15
+ curl -s -L https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux.run -o /tmp/tmp.zjJFZXEI15
+ cat /tmp/tmp.zjJFZXEI15
+ rm /tmp/tmp.zjJFZXEI15
+ sh /tmp/cuda/combined.sh --extract=/tmp/cuda
++ ls -1 '/tmp/cuda/cuda-linux.10.1.105*.run'
ls: cannot access '/tmp/cuda/cuda-linux.10.1.105*.run': No such file or directory
+ local LINUX=
+ --prefix=/opt/compiler-explorer/cuda/10.1.105 -noprompt -nosymlink -no-man-page
./update_compilers/install_nonfree_compilers.sh: line 101: --prefix=/opt/compiler-explorer/cuda/10.1.105: No such file or directory
Jul/13 14:10 admin-node~/compiler-explorer-image (master|✔) 2.9m $ 
[0] 0:fish* 1:fish-                                                                                                                                                         "fish  /home/ubuntu/co" 14:12 13-Jul-19
```

**Pull request merged**
