### PR TITLE
Install Swift 4.2

### PR DESCRIPTION
**Pull request by nuclearace**
Please let me know how I should go about testing this. I ran the install script locally and it did install the relevant compiler stuff to /opt/compiler-explorer/ but I'm not sure what other changes are needed to actually get things to work.

### CODE REVIEW

**Comment by RabsRincon** [comment]
Hi @nuclearace , thanks for taking the time to add and test this swift version.
If it installs correctly, you would want to open another PR on the main repo at https://github.com/mattgodbolt/compiler-explorer adding it to the swift compilers list (https://github.com/mattgodbolt/compiler-explorer/blob/master/etc/config/swift.amazon.properties).

Feel free to ask any questions you have should you have any other doubt
(Or check the wiki https://github.com/mattgodbolt/compiler-explorer/wiki/How-to-install-a-compiler for a more in-depth guide) :)

**Comment by nuclearace** [comment]
Thanks @RabsRincon. I've opened https://github.com/mattgodbolt/compiler-explorer/pull/1100

**Comment by RabsRincon** [comment]
Thank you! It should hit the live site either today or tomorrow morning :)

**Comment by nuclearace** [comment]
@RabsRincon do you know if that install happened or if there was some issue that popped up? I don't see 4.2 up yet.

**Comment by RabsRincon** [comment]
Yeah, sorry! We did not have the time to ensure that we can push a new version to prod yet. We should have done so by tomorrow evening.

Sorry to keep you waiting

**Pull request merged**
