### PR TITLE
Add a RISC-V GCC 8.2.0 Compiler

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
I'm not actually sure how this all works, so as a result I've given it
no testing aside from having built a crosstool-ng based toolchain for
RISC-V on my local machine (which is where I got the config).

Signed-off-by: Palmer Dabbelt <palmer@sifive.com>

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
I don't have root on the fast machines so I didn't run the script that touches /opt.  LMK if you want me to give it a shot on my laptap, but it might take a while...

**Comment by mattgodbolt** [comment]
Thanks for this! I'll merge and see if I can get this working and add it to `build_cross_compilers.sh` too!

**Comment by palmer-dabbelt** [comment]
Awesome!  I have no idea how this works in terms of integration into compile-explorer, but if you have any questions about the toolchain stuff I can try to answer them.

**Comment by mattgodbolt** [comment]
Thanks @palmer-dabbelt :) I'm hoping it'll all just come out in the wash shortly...mostly it's dreadful bash script hackery to get it in.

**Pull request merged**
