### PR TITLE
Automate addition of new stable LDC version

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
Pinging @JohanEngelen.

**Comment by apmorton** [comment]
Personally I would rather this remain a manual addition for each new stable version - this seems needlessly fragile. When any command returns non-zero the entire install script terminates, potentially preventing other nightly installs from happening.

Stable versions will still require a manual PR on the main CE repo to appear on the live site regardless, and we already have a nightly install that tracks the latest beta automatically.

**Comment by kinke** [comment]
To me, any manual step that can be automated for stuff like this should be, as it's just going to be outdated sooner or later otherwise (already the case for the DMD versions below). I assumed `fetch` had some fault-tolerant retry logic without wanting to dig into it.

**Comment by apmorton** [comment]
On the fragility front I wasn't so much concerned with random network failures as I was about the assumptions being made about version numbers.

What happens if ldc skips a minor version or bumps to 2.0.0?
What happens if ldc ships `1.x.2`?

I am not fundamentally opposed to this, but it doesn't solve the issue of automatically getting new compiler versions on the site.  It will get them on our disk, but someone still has to manually add them to https://github.com/mattgodbolt/compiler-explorer/blob/master/etc/config/d.amazon.properties before they will appear.

**Comment by kinke** [comment]
I've added a check wrt. the expected `1.xx.*` format. We've never skipped a minor version since v1.0 and aren't tied to the versioning of other components, so I don't see why we would anytime soon. There has been a single patch release since v1.0, v1.1.1, which isn't currently installed here, and the likelihood of patch releases has decreased substantially since the release cycle has been shortened to 2 months between stable releases. A problematic major version bump (or minor exceeding 2 chars) is checked now, emitting a warning and skipping all LDC v1.* installations in that case.

> it doesn't solve the issue of automatically getting new compiler versions on the site. It will get them on our disk, but someone still has to manually add them

I know, but 1 PR instead of 2 sounds like 50% less hassle to me. But it also sounds as if it could be trivially automated as well.

**Comment by JohanEngelen** [comment]
@apmorton What triggers running this script? I thought it was triggered by a new commit, but this won't work if that's the case.

**Comment by apmorton** [comment]
The script is run once every 24 hours by a cron job on our admin node

**Comment by JohanEngelen** [comment]
I don't have a strong opinion on this.

( One advantage of the manual addition is that this leaves some room for weeding out buggy versions. Compilers can never be removed from CE (because then old links stop working), so it can be nice to wait a little bit before adding a new compiler such that the list of compilers stays short and is not cluttered with version x.y.0 and x.y.1. )

**Comment by apmorton** [comment]
FWIW, I am happy to take ownership of adding new LDC versions from now on - it's a very quick change to make on our end.

Whenever a new release of LDC is out and is ready for CE just file an issue on either repo and tag/assign it to me and I can take care of the required changes.

**Comment by mattgodbolt** [comment]
I agree with @apmorton here: while I'm very glad of any automation, I think that adding and storing of new compilers should be an intentional thing. We can definitely have scripts to help us, but I still think it should be a human-driven process.

**Pull request closed without merging**
