### PR TITLE
Install binutils-multiarch so that clang cross-compilation works

### PR DESCRIPTION
**Pull request by shawnl**
Closes: #1353

### CODE REVIEW

**Comment by shawnl** [comment]
see https://packages.ubuntu.com/bionic/binutils-multiarch

**Comment by shawnl** [comment]
https://github.com/mattgodbolt/compiler-explorer/issues/1353

**Comment by mattgodbolt** [comment]
Thanks so much! I've typically built our own binutils so that we use the most recent binutils available for each compiler.

That said: this is a great way to get the cross-arch binutils stuff, and in lieu of the will to cross-compile and build all the binutilses I'm going to merge!

Thanks!

**Comment by mattgodbolt** [comment]
Oh wait! I merged without checking which Docker file this was in!

The file you modified is for us building the compilers themselves, not the container Compiler Explorer runs in.

**Pull request merged**
