### PR TITLE
Add Nim language and compiler (version 1.0.4)

### PR DESCRIPTION
**Pull request by DaemonSnake**
Continuation of https://github.com/mattgodbolt/compiler-explorer/pull/1753
For issue: https://github.com/mattgodbolt/compiler-explorer/issues/206

### CODE REVIEW

**Comment by RabsRincon** [comment]
I've seen that nim publishes nightly builds too. Do you have any plans to add support for it? The hard part is finding that latest build automatically from https://github.com/nim-lang/nightlies/releases right?

**Comment by RabsRincon** [comment]
TIL about `https://github.com/name/repo/releases/latest` redirecting to the latest published release

**Comment by DaemonSnake** [comment]
> I've seen that nim publishes nightly builds too. Do you have any plans to add support for it? The hard part is finding that latest build automatically from https://github.com/nim-lang/nightlies/releases right?

Yep next step is to add nightlies. The thing I'm missing is a way to get the version of the nightlies (for instance now 1.1.1) as it's backed into the package name and folder

**Comment by RabsRincon** [comment]
Just in case it's useful in this case, the rest of the nightly compilers are referred directly as trunk/nightly to avoid having to change names in the configs, and then if more information is needed, in the UI we surface the result of passing the result of calling the compilers with whatever the equivalent to the `--version` flag is.

**Pull request merged**
