### PR TITLE
Bump KALRAY K1 MPPA compiler version

### PR DESCRIPTION
**Pull request by dkm**
Update GCC from 7.4.1 to 7.5.0.

This corresponds to 4.0.0-cd9 from:
  https://github.com/kalray/gcc/releases
  https://github.com/kalray/newlib/releases
  https://github.com/kalray/gdb-binutils/releases

### CODE REVIEW

**Comment by apmorton** [comment]
Because this one changes the GCC version this definitely needs to be handled as a new compiler since the resulting install path is going to be different.

Can you please update the PR to restore the existing 7.4.1 build files?

**Comment by dkm** [comment]
Ok, sure. I thought that you only kept one version per major, sorry.

**Comment by apmorton** [comment]
generally speaking we keep *all* versions ever published to the site - but for a more niche architecture like kalray I think we can settle on a happy medium where we only keep the latest release for each toolchain version.

IE: if kalray tags a new release but doesn't bump to a newer upstream gcc version we can update in place (like we did last time).

**Comment by dkm** [comment]
> generally speaking we keep _all_ versions ever published to the site - but for a more niche architecture like kalray I think we can settle on a happy medium where we only keep the latest release for each toolchain version.
> 
> IE: if kalray tags a new release but doesn't bump to a newer upstream gcc version we can update in place (like we did last time).

Ok ! I'll follow these instructions for the next releases. We are still developing our backend and 7.4.1 contains known issues. I would understand if you want to keep it, even if it has bugs that won't be fixed for the sake of not breaking any existing links, but if that's not a problem, you should drop it from the live site :)

**Pull request merged**
