### PR TITLE
First stab at error page for non-running environments

### PR DESCRIPTION
**Pull request by apmorton**
it's butt ugly, but it should work - only way to find out is to run the terraform and update the admin site.

Maybe @RabsRincon can take a stab at the web design part of this once we know it works?

### CODE REVIEW

**Comment by apmorton** [comment]
Error page as it stands can be seen here: https://d3e106rr72m90r.cloudfront.net/

The page has 3 main layouts:
- [503 from production](https://d3e106rr72m90r.cloudfront.net/)
  - just displays some contact info
- [Down environment index page](https://d3e106rr72m90r.cloudfront.net/beta/)
  - only displays "Continue to Live Site" button
- [Down environment direct link ](https://d3e106rr72m90r.cloudfront.net/beta/z/vanRkM)
  - displays "Follow Link" and "Go Home" buttons

**Comment by RabsRincon** [comment]
I love this.

**Comment by apmorton** [comment]
Just want to get the logo designs signed off by @mattgodbolt and then it's good to go.

**Comment by mattgodbolt** [comment]
I love it! Ship it!

**Pull request merged**
