### PR TITLE
Add Advance Toolchain (IBM Power cross compiler) - gcc based

### PR DESCRIPTION
**Pull request by grooverdan**
Let me know if this is too big and I'll see what I can cut down.

Seems to need the following build dependencies (16.04) but assuming 18.04 is the same:
<pre>
apt-get install -y lsb-release  autoconf  automake libtool m4  bison sed flex perl \
        cvs debhelper dpkg-sig gawk libncurses5-dev libxml2-utils ncurses-term subversion texinfo xutils-dev zlib1g-dev \
        autoconf-archive dh-systemd docbook2x pkg-config \
        wget git
</pre>

closes #20 
closes #mattgodbolt/compiler-explorer/issues/205

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Hi @grooverdan 

Thanks for this! I'd very much prefer not building compilers in the `install_compilers.sh` script: especially unconditionally. It would mean the compiler update would take a very long time! :)

Instead we build the compilers separately, then `tar` them up and upload to S3 storage. This is how all the GCC and clang builds are done. These builds are done from within a Docker container that has all the necessary prerequistites (see for example https://github.com/mattgodbolt/compiler-explorer-image/blob/master/gcc/Dockerfile for some context).

This would be the first non-GCC or clang build and so it wasn't at all obvious that this is the way to proceed. My thoughts would be:

1. copy the `gcc` directory to be e.g. `ibm-power`. Make the necessary edits to the Dockerfile to install all the build dependencies.
2. Update the `build.sh` inside that docker image to build the compiler, installing it like the GCC ones do to a known good spot, then tar.xz-ing them. Ideally s3 uploading but I appreciate that's impossible to test...
3. change the `install_compilers.sh` to [a] check to see if the compiler's already installed, and if not [b] install it like the other compilers (with a `fetch` and an untar).
4. Make a separate PR to the main compiler-explorer repository to configure using the IBM power. Note that this PR does _not_ close https://github.com/mattgodbolt/compiler-explorer/issues/205 as that needs changes in the main repo too.

I appreciate this is a ton of extra work! I can probably use what you've done so as a template and try it out myself, but I thought in the spirit of sharing I'd explain as best as I can how I'd make the change and see if it's something you can do. I realise not everyone is a Docker user or knows anything about s3 and so on!

**Comment by grooverdan** [comment]
That sounds workable. I can work with docker, haven't done much with s3 however it looks like just a push so that should be manageable. As long as you're ok for  the docker to clone https://github.com/advancetoolchain/advance-toolchain (its light and just a build system) and I don't need to reinvent a cross compile build script from scratch I should be right.

**Comment by dbroemmel** [comment]
I know this initially only mentioned C++ and Go, but am I right in guessing Fortran compilers would/could be included in this as well?

**Comment by grooverdan** [comment]
Did start down this path, however after talking to AT maintainers the gcc branches/ibm/gcc-8-branch built using ct-ng in #127 seems easier.

**Pull request closed without merging**
